print("je suis fonction1")
print( "je suis le master")
print("insertion ica")
print( "je suis le master")
print("ajout ica")
print("insetion code cth")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")
print("j'avance tres tres tres vite ")